name: UnitTest

on:
  push:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        composer install --no-ansi --no-interaction --no-progress --prefer-dist
    - name: Copy .env
      run: |
        php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Generate key
      run: |
        php artisan key:generate
    - name: Show version
      run: |
        composer dbdb:version
    - name: Create and start databases
      run: |
        composer dbdb:mysql create-start --db-name=my-mysql-5 --db-version=8.0.30  --db-port=3306
        composer dbdb:redis create-start --db-name=my-redis-6 --db-version=6.2.6   --db-port=6379
    - name: Show databases
      run: |
        composer dbdb:list
    - name: Migrate
      run: |
        php artisan migrate --force
    - name: Execute tests
      run: |
        php artisan test
